apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: rakeshagrawal1502/helloworld:1.1
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true

      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname-system-msi
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld  
spec:
  type: ClusterIP
  ports:
  - port: 8083
  selector:
    app: helloworld