apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: rakeshagrawal1502/helloworld:1.0
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld  
spec:
  type: ClusterIP
  ports:
  - port: 8083
  selector:
    app: helloworld