# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  secretObjects:                               
  - secretName: cregsecrets
    data: 
    - objectName: mypwd
      key: mypwd
    type: Opaque
  parameters:
    usePodIdentity: "false"               # Set to true for using aad-pod-identity to access your key vault
    useVMManagedIdentity: "true"         # Set to true for using managed identity
    userAssignedIdentityID: ""         # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: cregkeyvault           # Set to the name of your key vault
    cloudName: ""        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: mypwd
          objectType: secret             # object types: secret, key, or cert
    tenantId: 6e735c51-2596-4fcd-bf69-6950d1e045ab                # The tenant ID of the key vault   